### ISSUE TITLE
"Stats folder not found, skipping synchronization..." with a non-default world name

### ISSUE THREAD

**Issue by MrScopi** [FNewel/Player-Statistics#1]
I have a non-default world name (e.g., it's not "world").  Because of this, it claims there is no stats folder.

Please add a config option for custom world names.

Thanks!  Looks great!

**Comment by FNewel** [comment]
Hey!
Thank you for reporting the problem. 

I'm currently focusing on fixing bugs (mod, website). When I manage to fix the major issues, I will dive into implementing and expanding the mod. 

I've written down the request for non-default world names in TODO and will resolve it as soon as I can.

**Comment by MrScopi** [comment]
Yes, my temporary workaround is to just copy the stats folder periodically. It works-ish!

Not making a new issue for this yet, but I use Geyser/Floodgate for Bedrock players.  They currently don't get names/icons, but I don't know if that's due to only copying the stats folder or not.

Thanks again!

**Comment by FNewel** [comment]
Oh, I see...
I hadn't thought of that at all. Bedrock players will not have the same UUID - nick - skin as Java players. The stats are stored under the UUID of the player... I then use the API to get the nick and skin of the player... But this will not work for Bedrock players, so neither the nick nor the skin is visible, I don't know if I can solve this problem at the moment since I don't have much experience with Bedrock... but I will think about it. 

If you use Discord, you can join me on the server and we can go over it more closely (file structure, Bedrock player data) and maybe we can find a solution.. This is the link to my discord server https://discord.gg/EBtW6HG4AH

**Comment by FNewel** [comment]
Custom folder and Bedrock players should be fixed in version [2.1.0](https://github.com/FNewel/Player-Statistics/releases/tag/2.1.0)
